const Theme = {

  // Positioning
  APP_DEFAULT_TOP: 35, // in percentage

  // Content
  CONTENT_DEFAULT_WIDTH: 200,
  CONTENT_DEFAULT_HEIGHT: 275,
  CONTENT_TITLE_HEIGHT: 34,
  CONTENT_SHADOW_SIZE: 12,
  CONTENT_INNER_MARGIN: 9,
  CONTENT_BACKGROUND_COLOR: '#463d2d',

  CONTENT_DEFAULT_POSITION_X: 0,
  SELECTABLE_CONTENT_CLASS: 'selectable-content',

  // Navigation
  NAV_ITEM_WIDTH: 100,
  NAV_ITEM_HEIGHT: 40,
  NAV_BACKGROUND_COLOR: '#463d2d',

  // Text
  LIGHT_TEXT_COLOR: '#ffffff',
  DARK_TEXT_COLOR: '#000',
  HIGHLIGHT_TEXT_COLOR: '#f8a200',
  HIGHLIGHT_HOVER_TEXT_COLOR: '#ffc600',
  CONTRAST_TEXT_COLOR: '#fdff00',
  TWITCH_TEXT_COLOR: '#b26df7',
  LIGHT_TWITCH_TEXT_COLOR: '#b29ab1',
  ERROR_TEXT_COLOR: 'rgb(255, 0, 0)',
  SUCCESS_TEXT_COLOR: 'rgb(13, 193, 13)',

  // Forms
  TEXTAREA_BACKGROUND_COLOR: '#41352c',
  TEXTAREA_BORDER_COLOR: '#1c0e0e',
};

export default Theme;
